server.port=8090
spring.application.name=zuul-server

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Rutas dinámicas
zuul.routes.autos.service-id=servicio-autos
zuul.routes.autos.path=/autos/**

zuul.routes.inventario.service-id=servicio-inventarioautos
zuul.routes.inventario.path=/inventario/**

# Hystrix timeout
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=1000
