spring.application.name= servicio-inventarioautos
server.port= 8004
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Hystrix 
feign.hystrix.enabled=true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=5000
hystrix.command.default.circuitBreaker.requestVolumeThreshold=5
hystrix.command.default.circuitBreaker.errorThresholdPercentage=50

# Endpoints
management.endpoints.web.exposure.include=hystrix.stream,health,info